{{/*
Inspired by bitnami library
*/}}

{{/*
Return the image name based on the global values and image configuration
{{ include "czertainly-lib.images.image" ( dict "image" .Values.image "global" .Values.global) }}
*/}}
{{- define "czertainly-lib.images.image" -}}
{{- $registryName := .image.registry -}}
{{- $repositoryName := .image.repository -}}
{{- $separator := ":" -}}
{{- $termination := .image.tag | toString -}}

{{- if .global }}
  {{- if .global.image.registry }}
    {{- $registryName = .global.image.registry -}}
  {{- end -}}
{{- end -}}

{{- if .image.digest }}
  {{- $separator = "@" -}}
  {{- $termination = .image.digest | toString -}}
{{- end -}}

{{- printf "%s/%s%s%s" $registryName $repositoryName $separator $termination -}}
{{- end -}}

{{/*
Return the secret names from the values
{{ include "czertainly-lib.images.pullSecrets" ( dict "images" (list .Values.image1, .Values.image2) "global" .Values.global) }}
*/}}
{{- define "czertainly-lib.images.pullSecrets" -}}
{{- $pullSecrets := list }}

{{- if .global }}
  {{- range .global.image.pullSecrets -}}
    {{- $pullSecrets = append $pullSecrets . -}}
  {{- end -}}
{{- end -}}

{{- range .images -}}
  {{- range .pullSecrets -}}
    {{- $pullSecrets = append $pullSecrets . -}}
  {{- end -}}
{{- end -}}

{{- if (not (empty $pullSecrets)) }}
imagePullSecrets:
  {{- range $pullSecrets }}
  - name: {{ . }}
  {{- end }}
{{- end }}
{{- end -}}