{{- /*
mylibchart.util.merge will merge two YAML templates and output the result.
This takes an array of three values:
- the top context
- the template name of the overrides (destination)
- the template name of the base (source)
*/}}
{{- define "czertainly-lib.util.merge" -}}
{{- $top := first . -}}
{{- $overrides := fromYaml (include (index . 1) $top) | default (dict ) -}}
{{- $tpl := fromYaml (include (index . 2) $top) | default (dict ) -}}
{{- toYaml (merge $overrides $tpl) -}}
{{- end -}}

{{- /*
this will take the databse values and convert to the jdbcUrl format
- type, host, port, name are taken from the global values
- the argument taken is the additional information that should be appended to jdbc url
- example (list $ . "?characterEncoding=UTF-8")
*/}}
{{- define "czertainly-lib.util.format.jdbcUrl" -}}
{{- $ := index . 0 }}
{{- $type := pluck "type" $.Values.global.database $.Values.database | compact | first -}}
{{- if eq $type "postgresql" -}}
{{- $append := index . 1 -}}
{{- $host := pluck "host" $.Values.global.database $.Values.database | compact | first -}}
{{- $port := pluck "port" $.Values.global.database $.Values.database | compact | first -}}
{{- $name := pluck "name" $.Values.global.database $.Values.database | compact | first -}}
{{- printf "jdbc:postgresql://%s:%s/%s%s" $host $port $name $append }}
{{- end -}}
{{- end -}}