apiVersion: apps/v1
kind: Deployment
metadata:
  name: ejbca-ng-connector-deployment
  labels:
    {{- include "ejbca-ng-connector.labels" . | nindent 4 }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "ejbca-ng-connector.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "ejbca-ng-connector.selectorLabels" . | nindent 8 }}
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    spec:
      {{- with .Values.global.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
      - name: ejbca-ng-connector
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        env:
        - name: PORT
          value: {{ .Values.service.port | quote }}
        - name: LOGGING_LEVEL_COM_CZERTAINLY
          value: {{ .Values.logging.level | quote }}
        - name: JDBC_URL
          value: {{ .Values.global.database.jdbcUrl | quote }}
        - name: JDBC_USERNAME
          valueFrom:
            secretKeyRef:
              name: ejbca-ng-connector-secret
              key: username
        - name: JDBC_PASSWORD
          valueFrom:
            secretKeyRef:
              name: ejbca-ng-connector-secret
              key: password
        ports:
          - containerPort: {{ .Values.service.port }}
      volumes:
        - name: ejbca-ng-connector-secret
          secret:
            secretName: ejbca-ng-connector-secret