apiVersion: v1
data:
  password: {{ .Values.global.database.password | b64enc | quote }}
  username: {{ .Values.global.database.username | b64enc | quote }}
kind: Secret
metadata:
  name: ejbca-ng-connector-secret