{{- $httpProxy := pluck "httpProxy" .Values.global .Values | compact | first }}
{{- $httpsProxy := pluck "httpsProxy" .Values.global .Values | compact | first }}
{{- $noProxy := pluck "noProxy" .Values.global .Values | compact | first }}
{{- $imagePullSecrets := pluck "imagePullSecrets" .Values.global .Values | compact | first }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ejbca-ng-connector-deployment
  labels:
    {{- include "ejbca-ng-connector.labels" . | nindent 4 }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "ejbca-ng-connector.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "ejbca-ng-connector.selectorLabels" . | nindent 8 }}
      annotations:
        # when the list of the trusted certificates is changed, restart deployment
        checksum/config: {{ include (print $.Template.BasePath "/trusted-certificates-secret.yaml") . | sha256sum }}
        {{- if .Values.global.trusted.certificates }}
        checksum/config: {{ include ("czertainly-lib.trusted.certificates.secret.global") . | sha256sum }}
        {{- end }}
      {{- with .Values.podAnnotations }}
        {{- toYaml . | nindent 8 }}
      {{- end }}
    spec:
      {{- include "ejbca-ng-connector.imagePullSecrets" . | indent 6 }}
      containers:
      - name: ejbca-ng-connector
        image: {{ include "ejbca-ng-connector.image" . }}
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        env:
        - name: PORT
          value: {{ .Values.service.port | quote }}
        {{- if $httpProxy }}
        - name: HTTP_PROXY
          value: {{ $httpProxy }}
        {{- end }}
        {{- if $httpsProxy }}
        - name: HTTPS_PROXY
          value: {{ $httpsProxy }}
        {{- end }}
        {{- if $noProxy }}
        - name: NO_PROXY
          value: {{ $noProxy }}
        {{- end }}
        - name: LOGGING_LEVEL_COM_CZERTAINLY
          value: {{ .Values.logging.level | quote }}
        - name: JDBC_URL
          value: {{ include "czertainly-lib.util.format.jdbcUrl" (list . "?characterEncoding=UTF-8") | quote }}
        - name: JDBC_USERNAME
          valueFrom:
            secretKeyRef:
              name: ejbca-ng-connector-secret
              key: username
        - name: JDBC_PASSWORD
          valueFrom:
            secretKeyRef:
              name: ejbca-ng-connector-secret
              key: password
        {{- if or .Values.global.trusted.certificates .Values.trusted.certificates }}
        - name: TRUSTED_CERTIFICATES
          valueFrom:
            secretKeyRef:
              {{- if .Values.global.trusted.certificates }}
              name: trusted-certificates
              {{- else if .Values.trusted.certificates }}
              name: trusted-certificates-{{ .Chart.Name | lower }}
              {{- end }}
              key: ca.crt
        {{- end }}
        ports:
          - containerPort: {{ .Values.service.port }}
