apiVersion: v1
kind: Service
metadata:
  name: ejbca-ng-connector-service
  labels:
    {{- include "ejbca-ng-connector.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      protocol: "TCP"
  selector:
    {{- include "ejbca-ng-connector.selectorLabels" . | nindent 4 }}