apiVersion: v1
kind: Service
metadata:
  name: auth-service
  labels:
    {{- include "auth-service.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      protocol: "TCP"
  selector:
    {{- include "auth-service.selectorLabels" . | nindent 4 }}