apiVersion: v1
kind: Service
metadata:
  name: auth-opa-policies-service
  labels:
    {{- include "auth-opa-policies.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      protocol: TCP
  selector:
    {{- include "auth-opa-policies.selectorLabels" . | nindent 4 }}
