{{- $httpProxy := pluck "httpProxy" .Values.global .Values | compact | first }}
{{- $httpsProxy := pluck "httpsProxy" .Values.global .Values | compact | first }}
{{- $noProxy := pluck "noProxy" .Values.global .Values | compact | first }}
{{- $imagePullSecrets := pluck "imagePullSecrets" .Values.global .Values | compact | first }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: software-cryptography-provider-deployment
  labels:
    {{- include "software-cryptography-provider.labels" . | nindent 4 }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "software-cryptography-provider.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "software-cryptography-provider.selectorLabels" . | nindent 8 }}
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    spec:
      {{- include "software-cryptography-provider.imagePullSecrets" . | indent 6 }}
      containers:
      - name: software-cryptography-provider
        image: {{ include "software-cryptography-provider.image" . }}
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        env:
        - name: PORT
          value: {{ .Values.service.port | quote }}
        {{- if $httpProxy }}
        - name: HTTP_PROXY
          value: {{ $httpProxy }}
        {{- end }}
        {{- if $httpsProxy }}
        - name: HTTPS_PROXY
          value: {{ $httpsProxy }}
        {{- end }}
        {{- if $noProxy }}
        - name: NO_PROXY
          value: {{ $noProxy }}
        {{- end }}
        - name: LOGGING_LEVEL_COM_CZERTAINLY
          value: {{ .Values.logging.level | quote }}
        - name: JDBC_URL
          value: {{ include "czertainly-lib.util.format.jdbcUrl" (list . "?characterEncoding=UTF-8") | quote }}
        - name: JDBC_USERNAME
          valueFrom:
            secretKeyRef:
              name: software-cryptography-provider-secret
              key: username
        - name: JDBC_PASSWORD
          valueFrom:
            secretKeyRef:
              name: software-cryptography-provider-secret
              key: password
        - name: TOKEN_DELETE_ON_REMOVE
          value: {{ .Values.tokenDelete | quote }}
        - name: JAVA_OPTS
          value: {{ .Values.javaOpts | quote }}
        ports:
          - containerPort: {{ .Values.service.port }}
