{{- if .Values.registerConnectors }}
apiVersion: batch/v1
kind: Job
metadata:
  name: "{{ .Release.Name }}"
  labels:
    {{- include "czertainly.labels" . | nindent 4 }}
    helm.sh/chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
  annotations:
    # This is what defines this resource as a hook. Without this line, the
    # job is considered part of the release.
    "helm.sh/hook": post-install
    "helm.sh/hook-weight": "-5"
    "helm.sh/hook-delete-policy": before-hook-creation,hook-succeeded
spec:
  template:
    metadata:
      name: "{{ .Release.Name }}"
      labels:
        app.kubernetes.io/managed-by: {{ .Release.Service | quote }}
        app.kubernetes.io/instance: {{ .Release.Name | quote }}
        helm.sh/chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    spec:
      restartPolicy: Never
      containers:
        - name: register-connectors-job
          image: "alpine/curl"
          command:
          - /bin/sh
          - -c
          - |
            while ! nc -z core-service {{ .Values.service.port }}; do sleep 1; done &&
            {{- if .Values.commonCredentialProvider.enabled }}
            curl -X POST -k -H 'content-type: application/json' \
            -d '{"name": "Common-Credential-Connector","url": "http://common-credential-provider-service:{{ .Values.commonCredentialProvider.service.port }}","authType": "none"}' \
            http://core-service:{{ .Values.service.port }}/api/v1/connector/register &&
            {{- end }}
            {{- if .Values.ejbcaNgConnector.enabled }}
            curl -X POST -k -H 'content-type: application/json' \
            -d '{"name": "EJBCA-NG-Connector","url": "http://ejbca-ng-connector-service:{{ .Values.ejbcaNgConnector.service.port }}","authType": "none"}' \
            http://core-service:{{ .Values.service.port }}/api/v1/connector/register &&
            {{- end }}
            {{- if .Values.msAdcsConnector.enabled }}
            curl -X POST -k -H 'content-type: application/json' \
            -d '{"name": "MS-ADCS-Connector","url": "http://ms-adcs-connector-service:{{ .Values.msAdcsConnector.service.port }}","authType": "none"}' \
            http://core-service:{{ .Values.service.port }}/api/v1/connector/register &&
            {{- end }}
            {{- if .Values.x509ComplianceProvider.enabled }}
            curl -X POST -k -H 'content-type: application/json' \
            -d '{"name": "X509-Compliance-Provider","url": "http://x509-compliance-provider-service:{{ .Values.x509ComplianceProvider.service.port }}","authType": "none"}' \
            http://core-service:{{ .Values.service.port }}/api/v1/connector/register &&
            {{- end }}
            {{- if .Values.networkDiscoveryProvider.enabled }}
            curl -X POST -k -H 'content-type: application/json' \
            -d '{"name": "Network-Discovery-Provider","url": "http://network-discovery-provider-service:{{ .Values.networkDiscoveryProvider.service.port }}","authType": "none"}' \
            http://core-service:{{ .Values.service.port }}/api/v1/connector/register &&
            {{- end }}
            echo "all done"
{{- end }}