apiVersion: v1
kind: Service
metadata:
  name: keystore-entity-provider-service
  labels:
    {{- include "keystore-entity-provider.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      protocol: "TCP"
  selector:
    {{- include "keystore-entity-provider.selectorLabels" . | nindent 4 }}
