# Default values for api-gateway-kong.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

global:
  image:
    registry: ""
    # array of secret names
    pullSecrets: []
  volumes:
    ephemeral:
      type: ""
      sizeLimit: ""
      storageClassName: ""
      custom: {}
  hostName: ""
  keycloak:
    # if enabled, it has precedence from OIDC configuration
    enabled: false
    # client secret must be set if keycloak is enabled
    clientSecret: ""
  utils:
    enabled: false
  messaging:
    remoteAccess: false

replicaCount: 1

image:
  # default registry name
  registry: docker.io
  repository: revomatico/docker-kong-oidc
  tag: 3.0.0-6
  # the digest to be used instead of the tag
  digest: ""
  pullPolicy: IfNotPresent
  # array of secret names
  pullSecrets: []
  # default security context
  securityContext:
    runAsNonRoot: true
    runAsUser: 100
    readOnlyRootFilesystem: true
  # probes configuration
  probes:
    liveness:
      enabled: true
      # custom probe command, will override the default one
      custom: {}
      initialDelaySeconds: 5
      timeoutSeconds: 5
      periodSeconds: 10
      successThreshold: 1
      failureThreshold: 3
    readiness:
      enabled: true
      # custom probe command, will override the default one
      custom: {}
      initialDelaySeconds: 5
      timeoutSeconds: 5
      periodSeconds: 10
      successThreshold: 1
      failureThreshold: 3
    startup:
      enabled: false
      # custom probe command, will override the default one
      custom: {}
      initialDelaySeconds: 10
      timeoutSeconds: 3
      periodSeconds: 15
      successThreshold: 1
      failureThreshold: 20
  resources: {}
    # We follow recommendations and general guidelines to manage resources from:
    # https://master.sdk.operatorframework.io/docs/best-practices/managing-resources/
    # We recommend default requests for CPU and Memory, leaving the limits as a conscious
    # choice for the user. If you do want to specify your own resources, uncomment the following
    # lines, adjust them as necessary, and remove the curly braces after 'resources'.
    # requests:
    #   cpu: 70m
    #   memory: 1100M
    # limits: {}

volumes:
  ephemeral:
    # available types are: memory, storage, custom
    type: memory
    sizeLimit: "10Mi"
    storageClassName: ""
    custom: {}
    #  emptyDir:
    #    sizeLimit: "10Mi"
    #    medium: "Memory"

nameOverride: ""
fullnameOverride: ""

podAnnotations: {}

podSecurityContext: {}
  # fsGroup: 2000

# kong admin and consumer ports
service:
  # See https://kubernetes.io/docs/concepts/services-networking/service/#publishing-services-service-types
  type: ClusterIP
  admin:
    port: 8001
    # Node port to be exposed for admin service (only works with service.type: NodePort)
    # choose port between 30000-32767
    nodePort: ""
  consumer:
    port: 8000
    # Node port to be exposed for consumer service (only works with service.type: NodePort)
    # choose port between 30000-32767
    nodePort: ""

hostName: "czertainly.local"

backend:
  core:
    service:
      name: "core-service"
      port: 8080
      apiUrl: "/api"
  fe:
    service:
      name: "fe-administrator-service"
      port: 8080
      baseUrl: "/administrator"
      apiUrl: "/api"
      loginUrl: "/login"
      logoutUrl: "/logout"

auth:
  header:
    cert:
      upstream: "X-APP-CERTIFICATE"
      downstream: "ssl-client-cert"

logging:
  level: "info"

# kong-oidc plugin: https://github.com/revomatico/kong-oidc
# this plugin inserts user data into X-USERINFO header
oidc:
  # if oidc is enabled, all client values must be present
  enabled: false
  client:
    # oidc client id
    id: czertainly
    # oidc client secret
    secret: s0qKH5qItTWoxpBt7Zrj348ZhZ7woAbk
    # realm used in www-authenticate response header
    realm: czertainly
    # oidc discovery endpoint
    discovery: https://server.com/.well-known/openid-configuration

# kong cors plugin: https://docs.konghq.com/hub/kong-inc/cors
cors:
  enabled: false
  # list of allowed domains for the Access-Control-Allow-Origin header
  origins:
    - '*'
  # list of values for the Access-Control-Expose-Headers header
  exposedHeaders:
    - X-Auth-Token

# https://docs.konghq.com/gateway/latest/reference/configuration/#trusted_ips
# To trust all IPs, set this value to "0.0.0.0/0,::/0"
trustedIps: ""

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 100
  targetCPUUtilizationPercentage: 80
  # targetMemoryUtilizationPercentage: 80

nodeSelector: {}

tolerations: []

affinity: {}

hostAliases:
  resolveInternalKeycloak: false
