annotations:
  category: trustLifecycleManagement
apiVersion: v2
appVersion: 1.1.0
name: common-credential-provider
description: A Helm chart for Common Credential Provider for CZERTAINLY platform.
home: https://github.com/3KeyCompany/CZERTAINLY-Common-Credential-Provider
icon: https://github.com/3KeyCompany/CZERTAINLY/blob/master/czertainly-logo/czertainly_sign_color.svg
keywords:
  - czertainly
  - trust
  - management
  - lifecycle
  - platform
  - credential
  - provider
maintainers:
  - name: CZERTAINLY
    email: info@czertainly.com
    url: https://github.com/3KeyCompany/CZERTAINLY-Helm-Charts
type: application
sources:
  - https://github.com/3KeyCompany/CZERTAINLY
  - https://www.czertainly.com
  - https://docs.czertainly.com
version: 0.1.0
