{{- $enabled := pluck "enabled" .Values.global.persistence .Values.persistence | compact | first -}}
{{- if $enabled }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: czertainly-data
  labels:
    {{- include "czertainly.labels" . | nindent 4 }}
  {{- $annotations := pluck "annotations" .Values.global.persistence .Values.persistence | compact | first -}}
  {{- if $annotations }}
  annotations: {{- $annotations | toYaml | nindent 4 }}
  {{- end }}
spec:
  {{- include "czertainly-lib.persistence.spec.template" . | nindent 2}}
{{- end }}
