{{- $username := pluck "username" .Values.global.database .Values.database | compact | first | b64enc | quote }}
{{- $password := pluck "password" .Values.global.database .Values.database | compact | first | b64enc | quote }}
{{- $messagingUsername := pluck "username" .Values.global.messaging .Values.messagingService.secret | compact | first | b64enc | quote }}
{{- $messagingPassword := pluck "password" .Values.global.messaging .Values.messagingService.secret | compact | first | b64enc | quote }}
apiVersion: v1
data:
  jdbcPassword: {{ $password }}
  jdbcUsername: {{ $username }}
  messagingUsername: {{ $messagingUsername }}
  messagingPassword: {{ $messagingPassword }}
kind: Secret
metadata:
  name: core-secret