apiVersion: v1
data:
  jdbcPassword: {{ .Values.global.database.password | b64enc | quote }}
  jdbcUsername: {{ .Values.global.database.username | b64enc | quote }}
  tsPassword: {{ randAlphaNum 10 | b64enc | quote }}
kind: Secret
metadata:
  name: core-secret