apiVersion: apps/v1
kind: Deployment
metadata:
  name: core-deployment
  labels:
    {{- include "czertainly.labels" . | nindent 4 }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "czertainly.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "czertainly.selectorLabels" . | nindent 8 }}
      annotations:
        # when the list of the trusted certificates is changed, restart deployment
        checksum/config: {{ include (print $.Template.BasePath "/trusted-certificates-secret.yaml") . | sha256sum }}
      {{- with .Values.podAnnotations }}
        {{- toYaml . | nindent 8 }}
      {{- end }}
    spec:
      {{- include "czertainly.imagePullSecrets" . | indent 6 }}
      initContainers:
        - name: wait-for-auth-service
          image: {{ include "czertainly.curl.image" . }}
          imagePullPolicy: {{ .Values.curl.image.pullPolicy }}
          command:
            - /bin/sh
            - -c
            - |
              while ! nc -z auth-service 80; do sleep 1; done &&
              while ! nc -z auth-opa-policies-service 80; do sleep 1; done &&
              echo "auth service seems to be started"
      containers:
        - name: czertainly-auth-opa
          image: {{ include "czertainly.opa.image" . }}
          imagePullPolicy: {{ .Values.opa.image.pullPolicy }}
          ports:
            - containerPort: 8181
          args:
            - "run"
            - "--server"
            - "--log-format=json-pretty"
            - "--set=decision_logs.console=true"
            - "--set=services.nginx.url=http://auth-opa-policies-service"
            - "--set=bundles.nginx.service=nginx"
            - "--set=bundles.nginx.resource=bundles/bundle.tar.gz"
        - name: czertainly-core
          image: {{ include "czertainly.image" . }}
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
            - name: AUDITLOG_ENABLED
              value: {{ .Values.logging.audit.enabled | quote }}
            - name: HEADER_ENABLED
              value: "true"
            - name: HEADER_NAME
              value: {{ .Values.auth.header.certificate | quote }}
            - name: AUTH_TOKEN_HEADER_NAME
              value: {{ .Values.auth.header.token | quote }}
            {{- if .Values.global.httpProxy }}
            - name: HTTP_PROXY
              value: {{ .Values.global.httpProxy }}
            {{- end }}
            {{- if .Values.global.httpsProxy }}
            - name: HTTPS_PROXY
              value: {{ .Values.global.httpsProxy }}
            {{- end }}
            {{- if .Values.global.noProxy }}
            - name: NO_PROXY
              value: {{ .Values.global.noProxy }}
            {{- end }}
            - name: JDBC_URL
              value: {{ include "czertainly-lib.util.format.jdbcUrl" (list . "?characterEncoding=UTF-8") | quote }}
            - name: JDBC_USERNAME
              valueFrom:
                secretKeyRef:
                  name: core-secret
                  key: jdbcUsername
            - name: JDBC_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: core-secret
                  key: jdbcPassword
            - name: TS_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: core-secret
                  key: tsPassword
            - name: LOGGING_LEVEL_COM_CZERTAINLY
              value: {{ .Values.logging.level | quote }}
            {{- if .Values.registerAdmin.enabled }}
            - name: ADMIN_CERT
              valueFrom:
                secretKeyRef:
                  name: admin-certificate-secret
                  key: tls.crt
            {{- end }}
            - name: OPA_BASE_URL
              value: "http://localhost:8181"
            - name: AUTH_SERVICE_BASE_URL
              value: "http://auth-service"
            {{- if or .Values.global.trusted.certificates .Values.trusted.certificates }}
            - name: TRUSTED_CERTIFICATES
              valueFrom:
                secretKeyRef:
                  name: trusted-certificates
                  key: ca.crt
            {{- end }}
            - name: JAVA_OPTS
              value: {{ .Values.javaOpts | quote }}
          ports:
            - containerPort: {{ .Values.service.port }}
          readinessProbe:
            tcpSocket:
              port: {{ .Values.service.port }}
            initialDelaySeconds: 3
            periodSeconds: 3
            failureThreshold: 10
          readinessProbe:
            tcpSocket:
              port: 8181
            initialDelaySeconds: 3
            periodSeconds: 3
            failureThreshold: 10
          {{- if .Values.registerAdmin.enabled }}
          lifecycle:
            postStart:
              exec:
                command:
                  - "sh"
                  - "-c"
                  - |
                    while ! nc -z localhost {{ .Values.service.port }}; do sleep 1; done &&
                    while ! nc -z localhost 8181; do sleep 1; done &&
                    ADMIN_CERT=$( echo $ADMIN_CERT | awk '{gsub(/[[:blank:]]/,""); print}' ) &&
                    ADMIN_CERT=$( echo $ADMIN_CERT | awk '{gsub(/-----BEGINCERTIFICATE-----/,""); print}' ) &&
                    ADMIN_CERT=$( echo $ADMIN_CERT | awk '{gsub(/-----ENDCERTIFICATE-----/,""); print}' ) &&
                    curl -X POST \
                    -H 'content-type: application/json' \
                    -d '
                     {
                        "username": "{{ .Values.registerAdmin.admin.username }}",
                        "description": "{{ .Values.registerAdmin.admin.description }}",
                        "firstName": "{{ .Values.registerAdmin.admin.name }}",
                        "lastName": "{{ .Values.registerAdmin.admin.surname }}",
                        "email": "{{ .Values.registerAdmin.admin.email }}",
                        "enabled": "true",
                        "certificateData": "'$ADMIN_CERT'",
                        "certificateUuid": ""
                     }' \
                     http://localhost:{{ .Values.service.port }}/api/v1/local/admins
          {{- end }}
