apiVersion: v1
data:
  # if the global values are defined, use it, otherwise use local values
  dbPassword: {{ pluck "password" .Values.global.database .Values.database | compact | first | b64enc | quote }}
  dbUsername: {{ pluck "username" .Values.global.database .Values.database | compact | first | b64enc | quote }}
  messagingPassword: {{ include "czertainly-lib.secrets.generate_static_password" (list .Release "messaging.password") | b64enc | quote }}
  messagingUsername: {{ .Values.messaging.username | b64enc | quote }}
  {{- include "czertainly-lib.messaging.secrets.password" (dict "global" .Values.global "release" .Release) | indent 2 }}
kind: Secret
metadata:
  name: scheduler-service-secret