annotations:
  category: trustLifecycleManagement
apiVersion: v2
appVersion: 2.7.1
name: czertainly
description: A Helm chart for CZERTAINLY platform.
home: https://github.com/3KeyCompany/CZERTAINLY
icon: https://github.com/3KeyCompany/CZERTAINLY/blob/master/czertainly-logo/czertainly_sign_color.svg
dependencies:
  - condition: global.keycloak.enabled
    name: keycloak-internal
    # repository: oci://harbor.3key.company/czertainly-helm
    repository: file://../keycloak-internal
    tags:
      - keycloak-internal
    version: 1.0.0-1-develop
    alias: keycloakInternal
  - condition: commonCredentialProvider.enabled
    name: common-credential-provider
    # repository: oci://harbor.3key.company/czertainly-helm
    repository: file://../common-credential-provider
    tags:
      - credential-provider
    version: 1.3.1-0-develop
    alias: commonCredentialProvider
  - condition: ejbcaNgConnector.enabled
    name: ejbca-ng-connector
    # repository: oci://harbor.3key.company/czertainly-helm
    repository: file://../ejbca-ng-connector
    tags:
      - authority-provider
      - discovery-provider
    version: 1.4.0-1-develop
    alias: ejbcaNgConnector
  - condition: msAdcsConnector.enabled
    name: ms-adcs-connector
    # repository: oci://harbor.3key.company/czertainly-helm
    repository: file://../ms-adcs-connector
    tags:
      - authority-provider
      - discovery-provider
    version: 1.4.0-1-develop
    alias: msAdcsConnector
  - condition: x509ComplianceProvider.enabled
    name: x509-compliance-provider
    # repository: oci://harbor.3key.company/czertainly-helm
    repository: file://../x509-compliance-provider
    tags:
      - compliance-provider
    version: 1.2.0
    alias: x509ComplianceProvider
  - condition: cryptosenseDiscoveryProvider.enabled
    name: cryptosense-discovery-provider
    # repository: oci://harbor.3key.company/czertainly-helm
    repository: file://../cryptosense-discovery-provider
    tags:
      - cryptosense-discovery-provider
    version: 1.3.0
    alias: cryptosenseDiscoveryProvider
  - condition: networkDiscoveryProvider.enabled
    name: network-discovery-provider
    # repository: oci://harbor.3key.company/czertainly-helm
    repository: file://../network-discovery-provider
    tags:
      - discovery-provider
    version: 1.3.1-0-develop
    alias: networkDiscoveryProvider
  - condition: keystoreEntityProvider.enabled
    name: keystore-entity-provider
    # repository: oci://harbor.3key.company/czertainly-helm
    repository: file://../keystore-entity-provider
    tags:
      - entity-provider
    version: 1.3.0
    alias: keystoreEntityProvider
  - condition: softwareCryptographyProvider.enabled
    name: software-cryptography-provider
    # repository: oci://harbor.3key.company/czertainly-helm
    repository: file://../software-cryptography-provider
    tags:
      - cryptography-provider
    version: 1.1.0
    alias: softwareCryptographyProvider
  - condition: utilsService.enabled
    name: utils-service
    # repository: oci://harbor.3key.company/czertainly-helm
    repository: file://../utils-service
    tags:
      - utils-service
    version: 1.0.0-1-develop
    alias: utilsService
  # the following are mandatory dependencies
  - name: czertainly-lib
    # repository: oci://harbor.3key.company/czertainly-helm
    repository: file://../czertainly-lib
    version: 1.2.0
  - name: api-gateway-kong
    # repository: oci://harbor.3key.company/czertainly-helm
    repository: file://../api-gateway-kong
    tags:
      - api-gateway
    version: 3.0.0-6-3-develop
    alias: apiGateway
  - name: fe-administrator
    # repository: oci://harbor.3key.company/czertainly-helm
    repository: file://../fe-administrator
    tags:
      - fe
    version: 2.7.1-0-develop
    alias: feAdministrator
  - name: auth-service
    # repository: oci://harbor.3key.company/czertainly-helm
    repository: file://../auth-service
    tags:
      - auth
    version: 1.1.0
    alias: authService
  - name: auth-opa-policies
    # repository: oci://harbor.3key.company/czertainly-helm
    repository: file://../auth-opa-policies
    tags:
      - auth
      - opa
    version: 1.1.0
    alias: authOpaPolicies
keywords:
  - czertainly
  - certificate
  - cryptography
  - management
  - lifecycle
  - platform
maintainers:
  - name: CZERTAINLY
    email: info@czertainly.com
    url: https://github.com/3KeyCompany/CZERTAINLY-Helm-Charts
type: application
sources:
  - https://github.com/3KeyCompany/CZERTAINLY
  - https://www.czertainly.com
  - https://docs.czertainly.com
version: 2.7.1-0-develop
