{{- if not .Values.global.config.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: messaging-configmap
data:
  {{- include "czertainly-lib.messaging.configmap" (dict "global" .Values.global "messagingService" .Values) | indent 2 }}
{{- end }}
