{{- $messagingHttpPort := .Values.service.client.http }}
{{- $messagingAmqpPort := .Values.service.client.amqp }}
apiVersion: v1
kind: Service
metadata:
  name: messaging-service
  labels:
    {{- include "messaging-rabbitmq.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.client.type }}
  ports:
    - name: http
      port: {{ $messagingHttpPort }}
      protocol: "TCP"
    - name: amqp
      port: {{ $messagingAmqpPort }}
      protocol: "TCP"
  selector:
    {{- include "messaging-rabbitmq.selectorLabels" . | nindent 4 }}