apiVersion: v1
data:
  user: {{ .Values.secret.user | b64enc | quote }}
  pass: {{ .Values.secret.pass | b64enc | quote }}
  cookie: {{ .Values.secret.cookie | b64enc | quote }}
kind: Secret
metadata:
  name: messaging-secret