{{- $messagingUsername := pluck "username" .Values.global.messaging .Values.secret | compact | first }}
{{- $messagingPassword := pluck "password" .Values.global.messaging .Values.secret | compact | first }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: messaging-definitions
data:
  definitions.json: |
    {
      "rabbit_version": "3.12.0",
      "rabbitmq_version": "3.12.0",
      "product_name": "RabbitMQ",
      "product_version": "3.12.0",
      "users": [
        {
          "name": "{{ $messagingUsername }}",
          "password": "{{ $messagingPassword }}",
          "tags": [
            "administrator"
          ],
          "limits": {}
        }
      ],
      "vhosts": [
        {
          "name": "czertainly"
        }
      ],
      "permissions": [
        {
          "user": "{{ $messagingUsername }}",
          "vhost": "czertainly",
          "configure": ".*",
          "write": ".*",
          "read": ".*"
        }
      ]
    }
