{{- $messagingUsername := pluck "defaultUsername" .Values.global.messaging .Values.secret | compact | first | b64enc | quote }}
{{- $messagingPassword := pluck "defaultPassword" .Values.global.messaging .Values.secret | compact | first | b64enc | quote }}
apiVersion: v1
data:
  username: {{ $messagingUsername }}
  password: {{ $messagingPassword }}
  cookie: {{ .Values.secret.cookie | b64enc | quote }}
kind: Secret
metadata:
  name: messaging-secret