# Default values for keystore-entity-provider.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

nameOverride: ""
fullnameOverride: ""

# Global parameters that will overwrite local parameters
global:
  image:
    registry: ""
    # array of secret names
    pullSecrets: []
  volumes:
    ephemeral:
      type: ""
      sizeLimit: ""
      storageClassName: ""
      custom: {}
  database:
    type: ""
    host: ""
    port: ""
    name: ""
    username: ""
    password: ""
  httpProxy: ""
  httpsProxy: ""
  noProxy: ""

database:
  # currently only postgresql is supported
  type: "postgresql"
  host: "host.docker.internal"
  port: 5432
  name: "czertainlydb"
  username: "czertainlyuser"
  password: "your-strong-password"
httpProxy: ""
httpsProxy: ""
noProxy: ""

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 100
  targetCPUUtilizationPercentage: 80
  # targetMemoryUtilizationPercentage: 80
replicaCount: 1

service:
  type: "ClusterIP"
  port: 8080

image:
  # default registry name
  registry: docker.io
  repository: 3keycompany/czertainly-software-cryptography-provider
  tag: 1.0.0
  # the digest to be used instead of the tag
  digest: ""
  pullPolicy: IfNotPresent
  # array of secret names
  pullSecrets: []
  # default security context
  securityContext:
    runAsNonRoot: true
    runAsUser: 10001
    readOnlyRootFilesystem: true
  # probes configuration
  probes:
    liveness:
      enabled: true
      # custom probe command, will override the default one
      custom: {}
      initialDelaySeconds: 60
      timeoutSeconds: 5
      periodSeconds: 10
      successThreshold: 1
      failureThreshold: 3
    readiness:
      enabled: true
      # custom probe command, will override the default one
      custom: {}
      initialDelaySeconds: 60
      timeoutSeconds: 5
      periodSeconds: 10
      successThreshold: 1
      failureThreshold: 3
    startup:
      enabled: false
      # custom probe command, will override the default one
      custom: {}
      initialDelaySeconds: 60
      timeoutSeconds: 5
      periodSeconds: 10
      successThreshold: 1
      failureThreshold: 10

volumes:
  ephemeral:
    # available types are: memory, storage, custom
    type: memory
    sizeLimit: "1Mi"
    storageClassName: ""
    custom: {}
    #  emptyDir:
    #    sizeLimit: "10Mi"
    #    medium: "Memory"

logging:
  level: "INFO"

tokenDelete: "false"
javaOpts: ""

podAnnotations: {}

podSecurityContext: {}
  # fsGroup: 2000
