{{- $imagePullSecrets := pluck "imagePullSecrets" .Values.global .Values | compact | first }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: fe-administrator-deployment
  labels:
    {{- include "fe-administrator.labels" . | nindent 4 }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "fe-administrator.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "fe-administrator.selectorLabels" . | nindent 8 }}
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    spec:
      {{- include "fe-administrator.imagePullSecrets" . | indent 6 }}
      containers:
        - name: fe-administrator
          image: {{ include "fe-administrator.image" . }}
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
            - name: BASE_URL
              value: {{ .Values.url.base | quote }}
            - name: API_URL
              value: {{ .Values.url.api | quote }}
            - name: LOGIN_URL
              value: {{ .Values.url.login | quote }}
            - name: LOGOUT_URL
              value: {{ .Values.url.logout | quote }}
          ports:
            - containerPort: {{ .Values.service.port }}