apiVersion: v1
kind: Service
metadata:
  name: fe-administrator-service
  labels:
    {{- include "fe-administrator.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      protocol: "TCP"
  selector:
    {{- include "fe-administrator.selectorLabels" . | nindent 4 }}