# Default values for auth-service.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

nameOverride: ""
fullnameOverride: ""

# Global parameters that will overwrite local parameters
global:
  image:
    registry: ""
    # array of secret names
    pullSecrets: []
  database:
    type: ""
    host: ""
    port: ""
    name: ""
    username: ""
    password: ""
  trusted:
    certificates: ""
  httpProxy: ""
  httpsProxy: ""
  noProxy: ""

database:
  # currently only postgresql is supported
  type: "postgresql"
  host: "host.docker.internal"
  port: 5432
  name: "czertainlydb"
  username: "czertainlyuser"
  password: "your-strong-password"
trusted:
  certificates: ""
httpProxy: ""
httpsProxy: ""
noProxy: ""

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 100
  targetCPUUtilizationPercentage: 80
  # targetMemoryUtilizationPercentage: 80
replicaCount: 1

service:
  type: "ClusterIP"
  port: 8080

image:
  # default registry name
  registry: docker.io
  repository: 3keycompany/czertainly-auth
  tag: 1.0.0
  # the digest to be used instead of the tag
  digest: ""
  pullPolicy: IfNotPresent
  # array of secret names
  pullSecrets: []
  # default security context
  securityContext:
    runAsNonRoot: true
    runAsUser: 10001
    readOnlyRootFilesystem: true

logging:
  level: "INFO"

createUnknownUsers: "false"
createUnknownRoles: "false"

serviceAccount:
  # Specifies whether a service account should be created
  create: true
  # Annotations to add to the service account
  annotations: {}
  # The name of the service account to use.
  # If not set and create is true, a name is generated using the fullname template
  name: ""

podAnnotations: {}

podSecurityContext: {}
# fsGroup: 2000
