apiVersion: apps/v1
kind: Deployment
metadata:
  name: common-credential-provider-deployment
  labels:
    {{- include "common-credential-provider.labels" . | nindent 4 }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "common-credential-provider.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "common-credential-provider.selectorLabels" . | nindent 8 }}
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    spec:
      {{- with .Values.global.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
        - name: common-credential-provider
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
            - name: PORT
              value: "8080"
            - name: INCLUDE_ERROR
              value: "always"
          ports:
            - containerPort: 8080