apiVersion: v1
kind: Service
metadata:
  labels:
    {{- include "common-credential-provider.labels" . | nindent 4 }}
  name: common-credential-provider-service
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      protocol: "TCP"
  selector:
    {{- include "common-credential-provider.selectorLabels" . | nindent 4 }}
