name: Check Charts for develop
on:
  pull_request:
    branches: [develop]
  workflow_dispatch:

jobs:
  check:
    name: Check
    runs-on: ubuntu-latest

    services:
      # Label used to access the service container
      postgres:
        # Docker Hub image
        image: postgres:15
        # Provide the password for postgres
        env:
          POSTGRES_PASSWORD: your-strong-password
        ports:
          - 5432:5432
        # Set health checks to wait until postgres has started
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        volumes:
          - initdb/init-czertainlydb.sh:/docker-entrypoint-initdb.d/init-czertainlydb.sh

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0  # Shallow clones should be disabled for a better relevancy of analysis

      - name: Set up Helm
        uses: azure/setup-helm@v3
        with:
          version: v3.10.0

      - uses: actions/setup-python@v4
        with:
          python-version: '3.9'
          check-latest: true

      - name: Set up chart-testing
        uses: helm/chart-testing-action@v2.3.1

      - name: Run chart-testing (list-changed)
        id: list-changed
        run: |
          changed=$(ct list-changed --target-branch develop)
          echo "${changed}"
          if [[ -n "$changed" ]]; then
            echo "changed=true" >> $GITHUB_ENV
          
            # multiline string
            echo "changed_charts<<EOF" >> $GITHUB_ENV
            echo "$changed" >> $GITHUB_ENV
            echo "EOF" >> $GITHUB_ENV
          fi

      - name: Check if chart version is develop
        if: env.changed == 'true'
        env:
          changed_charts: ${{ env.changed_charts }}
        run: |
          #echo "${changed}"
          #echo "${changed_charts}"
          for CHART in $changed_charts
          do
            echo "Checking chart $CHART for develop version"
            version=$(yq ".version" < ${CHART}/Chart.yaml)
            if [[ $version != *-develop ]]; then
              echo "Chart $CHART changed, but not intended for develop" 
              exit 1
            fi
          done

      - name: Run chart-testing (lint)
        run: ct lint --target-branch develop --check-version-increment=false

      - name: Create kind cluster
        uses: helm/kind-action@v1.4.0
        if: env.changed == 'true'

      - name: Run chart-testing (install)
        run: ct install --target-branch develop --excluded-charts czertainly-lib
