apiVersion: v1
kind: Service
metadata:
  labels:
    {{- include "utils-service.labels" . | nindent 4 }}
  name: utils-service-service
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      protocol: "TCP"
  selector:
    {{- include "utils-service.selectorLabels" . | nindent 4 }}
